version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weather-alert"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kfaiqr8dsv78"
s3_prefix = "weather-alert"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
