AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for weather-alert

Resources:
  WeatherAlertStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/weather-alert.asl.json
      DefinitionSubstitutions:
        GetYrNoForecastArn: !GetAtt GetYrNoForecastFunction.Arn
        MapToConditionsMetArn: !GetAtt MapToConditionsMetFunction.Arn
        SendAlertFunctionArn: !GetAtt SendAlertFunction.Arn
      Events:
        HourlyTradingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(1 hour)"
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GetYrNoForecastFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref MapToConditionsMetFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SendAlertFunction

  GetYrNoForecastFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/clients/get-yrno-forecast/
      Handler: handler.handler
      Runtime: nodejs16.x

  MapToConditionsMetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/map-to-conditions-met/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

  SendAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/send-alert/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  WeatherAlertStateMachineArn:
    Description: "Weather Alert state machine ARN"
    Value: !Ref WeatherAlertStateMachine
  WeatherAlertStateMachineRole:
    Description: "IAM Role created for Weather Alert state machine based on the specified SAM Policy Templates"
    Value: !GetAtt WeatherAlertStateMachineRole.Arn
